name: Pull Request Target

on: pull_request_target

env: 
  DEMO_PLAIN: plain-text
  DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $DEMO_PLAIN from fork
      - run: echo $DEMO_SECRET from fork
        